### ISSUE TITLE
Error on loading drupal_dblog

### ISSUE THREAD

**Issue by anoopl** [elastic/logstash-contrib#105]
on Logstash version 1.4.2 installed using yum repo

While using drupal_dblog I get this error:

The error reported is: 
  cannot load Java class com.mysql.jdbc.Driver

IRB output:

/opt/logstash/bin/logstash irb
irb(main):001:0> require "jdbc/mysql"
=> true

irb(main):005:0> require "java"
=> false
irb(main):006:0> java_import "com.mysql.jdbc.Driver"
NameError: cannot load Java class com.mysql.jdbc.Driver

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-input-drupal_dblog/issues/9. Let's continue the discussion there! :)
