### ISSUE TITLE
Allow elasticsearch filter to use query DSL instead of query string

### ISSUE THREAD

**Issue by kurtado** [elastic/logstash-contrib#122]
Instead of the Lucene query string, the filter should allow the user to specify an Elasticsearch query DSL JSON object. 

The config might look something like this:
```
elasticsearch {
  query_dsl => { ..... }
}
```
We'd need to decide what would happen if both query DSL and query string were included in the config...

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-filter-elasticsearch/issues/13. Let's continue the discussion there! :)
