### ISSUE TITLE
JIRA plugin, add support for more fields

### ISSUE THREAD

**Issue by elvarb** [elastic/logstash-contrib#125]
Currently it seems you can only add info to the Summary field, a minimum requirement would be to add the Description field. Best case, any field

Config could look like this

```
jira {
   summary => "This is the summary"
   description => "This is the description"
   customfield => ["Field1","Content1",
             "Field2","Content2"]
}
```

**Comment by wiibaa** [comment]
@suyograo Dup of https://github.com/logstash-plugins/logstash-output-jira/issues/4
