### ISSUE TITLE
JMX input plugin: add support for arrays, collections 

### ISSUE THREAD

**Issue by roomsg** [elastic/logstash-contrib#128]
It's really cool to be able to have an input plugin for JMX ! 
However, currently, not all data (arrays, collections) gets properly handled:

examples:
- [arrays]
"metric_path" => "java.lang:type=GarbageCollector,name=ParNew.MemoryPoolNames",
"metric_value_string" => "[Ljava.lang.String;@25647d72"

- [collections]: 
"metric_path" => "java.lang:type=GarbageCollector,name=ParNew.LastGcInfo.memoryUsageBeforeGc",
  "metric_value_string" => "{#<Java::JavaUtil::Collections::UnmodifiableRandomAccessList:0x4f722930>=>#<Java::JavaxManagementOpenmbean::CompositeDataSupport:0x4fee370f>, #<Java::JavaUtil::Collections::UnmodifiableRandomAccessList:0x6091b85>=>#<Java::JavaxManagementOpenmbean::CompositeDataSupport:0x3fedbbdb>, #<Java::JavaUtil::Collections::UnmodifiableRandomAccessList:0x49669be>=>#<Java::JavaxManagementOpenmbean::CompositeDataSupport:0x2ef83b4c>, #<Java::JavaUtil::Collections::UnmodifiableRandomAccessList:0x1f12e637>=>#<Java::JavaxManagementOpenmbean::CompositeDataSupport:0x11c834d1>, #<Java::JavaUtil::Collections::UnmodifiableRandomAccessList:0x73f5504>=>#<Java::JavaxManagementOpenmbean::CompositeDataSupport:0x4ee67d53>}"

environment:
'logstash(-contrib)': 1.4.0
'jmx': milestone1 (jmx4r-0.1.4)
os: linux-centos6
jvm: Java HotSpot(TM) 64-Bit Server VM (build 24.51-b03, mixed mode)

**Comment by suyograo** [comment]
Dup of https://github.com/logstash-plugins/logstash-input-jmx/issues/8
