### ISSUE TITLE
WMI Input has memory leak on Windows

### ISSUE THREAD

**Issue by adaam** [elastic/logstash-contrib#129]
When i use WMI input at config, i found it continually increase memory use, and interval is same as default setting at WMI module (10 sec), maybe somewhere cause this, jruby-win32ole or else?

**Comment by rudibroekhuizen** [comment]
Thanks for your message. Could it be a bug in Windows? I've seen more issues with memory and wmi on the internet, for example: http://blogs.technet.com/b/kevinholman/archive/2010/06/09/wmi-leaks-memory-on-server-2008-r2-monitored-agents.aspx#pi10475=3.

**Comment by barakSpoj** [comment]
I don't think so since the process which is leaking is the JVM one. I made a few dumps during its work but there wasn't any class standing out more then the rest or even a clue for the leaking object.

I have found this post:
https://www.ruby-forum.com/topic/202041

It says the reason has something to do with parameters memory mapping of the win32ole, I couldn't find the actual fix thought..

**Comment by rudibroekhuizen** [comment]
You might be interested in my logstash and kibana configs to get analytics from Windows machines:
https://github.com/rudibroekhuizen/puppet-windows_role_logstash/tree/master/files

**Comment by barakSpoj** [comment]
Hey,

It is very similar to our configurations. The WMI plugin which you are using there is the bugged one.
What I did is to write an external tool to run the wmi, and rewrited the plugin so it will call that tool and parse the output result.

**Comment by rudibroekhuizen** [comment]
That sounds good! Can I find your version on GitHub?

**Comment by barakSpoj** [comment]
Hey,

I haven't uploaded the tool since its an external one written in .net (Yeah i know :P),
Also I've made some adjustments to the wmi plugin to call this tool.
I can upload everything here if u like, its quite easy to implement.

**Comment by rudibroekhuizen** [comment]
Take a look a my workaround. It uses the convertto-json option in powershell 4: https://github.com/rudibroekhuizen/puppet-windows_role_logstash/blob/master/files/logstash-win-base-20.conf. I just started it, hopefully no memory issue with this solution.

**Comment by barakSpoj** [comment]
Looks really good, more elegant than my solution for sure.

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-input-wmi/issues/5. Let's continue the discussion there! :)
