### ISSUE TITLE
Package building failed

### ISSUE THREAD

**Issue by eythian** [elastic/logstash-contrib#130]
logstash-contrib/pkg$ ./build.sh ubuntu 14.04
make: Map '/home/robin/catalyst/logstash-contrib' wordt binnengegaan
make: Map '/home/robin/catalyst/logstash-contrib' wordt verlaten
make: Map '/home/robin/catalyst/logstash-contrib' wordt binnengegaan
make: '.VERSION.mk' is bijgewerkt.
make: Map '/home/robin/catalyst/logstash-contrib' wordt verlaten
Building package for ubuntu 14.04
make: Map '/home/robin/catalyst/logstash-contrib' wordt binnengegaan
 ==> Downloading jruby 1.7.11
=> Ensuring ruby gems dependencies are in vendor/bundle...
Fetching and installing gem: bundler (>= 1.3.5)
Fetching: bundler-1.7.4.gem (100%)
Successfully installed bundler-1.7.4
1 gem installed
Fetching gem metadata from https://rubygems.org/.......
Resolving dependencies.......
Installing addressable 2.3.6
Installing extlib 0.9.16
...
Installing varnish-rb 0.2.0
Using bundler 1.7.4
Your bundle is complete!
It was installed into ./vendor/bundle
Post-install message from heroku:
 !    The `heroku` gem has been deprecated and replaced with the Heroku Toolbelt.
 !    Download and install from: https://toolbelt.heroku.com
 !    For API access, see: https://github.com/heroku/heroku.rb
Post-install message from httparty:
When you HTTParty, you must party hard!
=> Preparing tarball
make[1]: Map '/home/robin/catalyst/logstash-contrib' wordt binnengegaan
mkdir build/tarball
mkdir build/tarball/logstash-contrib-1.5.0.dev
make[1]: Map '/home/robin/catalyst/logstash-contrib' wordt verlaten
dirname: ontbrekend argument
Typ 'dirname --help' voor meer informatie.
basename: ontbrekend argument
Typ 'basename --help' voor meer informatie.
tar: U dient een van de opties '-Acdtrux', '--delete', of '--test-label' op te geven
Typ 'tar --help' of 'tar --usage' voor meer informatie.
=> tarball ready: build/logstash-contrib-1.5.0.dev.tar.gz
make: Map '/home/robin/catalyst/logstash-contrib' wordt verlaten

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
tar (child): build/ubuntu/logstash-contrib-1.5.0.dev.tar.gz: Functie open() is mislukt: Bestand of map bestaat niet
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
find: ‘*/’: Bestand of map bestaat niet
./build.sh: regel 105: cd: logstash-contrib-1.5.0.dev: Bestand of map bestaat niet
found ".." dir in relative path: ../build/ubuntu/opt/logstash
rsync error: syntax or usage error (code 1) at flist.c(2222) [sender=3.1.0]
ERROR: Unrecognised option '--ignore-iteration-in-dependencies'

See: 'fpm --help'

**Comment by jordansissel** [comment]
Two things, logstash-contrib has been split into many individual repos (see https://github.com/logstash-plugins, one plugin per repo) and the 'contrib' package is gone in favor of individual plugins. You can find out more details [here in our blog post](https://www.elastic.co/blog/plugin-ecosystem-changes).

As to your packaging error, I'm not sure. Given 1.5.0 is now available and contrib is gone from it, I'm not sure this is still a problem.
