### ISSUE TITLE
bigquery Plugin Intermident `IOError: closed stream`

### ISSUE THREAD

**Issue by tshauck** [elastic/logstash-contrib#135]
Hi,

I'm using the big query plugin, and I'm getting the following error from time to time. 

```
IOError: closed stream
           fsync at org/jruby/RubyIO.java:1898
  method_missing at /Users/thauck/src/logstash/lib/logstash/outputs/google_bigquery.rb:565
         receive at /Users/thauck/src/logstash/lib/logstash/outputs/google_bigquery.rb:200
          handle at /Users/thauck/src/logstash/lib/logstash/outputs/base.rb:86
      initialize at (eval):39
            call at org/jruby/RubyProc.java:271
          output at /Users/thauck/src/logstash/lib/logstash/pipeline.rb:266
    outputworker at /Users/thauck/src/logstash/lib/logstash/pipeline.rb:225
   start_outputs at /Users/thauck/src/logstash/lib/logstash/pipeline.rb:152
make: *** [stash-debug] Error 1
```

It seems to work when I'm just inserting a few lines a time, but when I attempt to crank up the lines I get the error.

I'm using Logstash 1.4.2, on OSX.

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-output-google_bigquery/issues/9. Let's continue the discussion there! :)
