### ISSUE TITLE
NSQ as input

### ISSUE THREAD

**Issue by rtoma** [elastic/logstash-contrib#138]
Hi all,

Redis is a great middleware between any logshipper and logstash, but once the memory buffer in redis is full you start to loose events.

What about adding support for NSQ (bitly's realtime distributed messaging platform, more on http://nsq.io)? A pretty complete Ruby library exists at https://github.com/chrisroberts/krakow

Regards,
Renzo

**Comment by jordansissel** [comment]
> once the memory buffer in redis is full you start to loose events.

Logstash shouldn't be losing events if redis is out of memory. If you've observed that, I'd love for some more details, if you have the energy! Let us know at https://github.com/logstash-plugins/logstash-output-redis/issues

**Comment by jordansissel** [comment]
In terms of NSQ, we recently published docs on [how to write an input plugin](https://www.elastic.co/guide/en/logstash/current/_how_to_write_a_logstash_input_plugin.html) and [how to write an output plugin](https://www.elastic.co/guide/en/logstash/current/_how_to_write_a_logstash_output_plugin.html), if this helps you get started :)

**Comment by mschneider82** [comment]
Try plugin install logstash-input-nsq
