### ISSUE TITLE
what does xml filter do?

### ISSUE THREAD

**Issue by kantjessica** [elastic/logstash-contrib#147]
Hi,

I am currently trying to use xml filter to parse my xml. Unfortunately, this filter does not work as smart as I expect. I expect a json output for my xml file. Instead it just identifies a few attributes inside of some tags, but not tags themselves. The definition of a tag or attribute can be found here http://en.wikipedia.org/wiki/XML.

So I am wondering how I can work with this filter in order to get a json-like object?

Best wishes,
Huiying

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-filter-xml/issues/12. Let's continue the discussion there! :)
