### ISSUE TITLE
Infinite loop on WMI input.

### ISSUE THREAD

**Issue by barakSpoj** [elastic/logstash-contrib#150]
Hi,

Wanted to point out a potential bug on wmi.rb. on row 70 there is a retry command in case of exception
raise. The problem is in case of error on the WMI socket connection, there is no re-connection command and a straight jump to the query all over again what might cause an infinite loop.
I suggest either to remove the retry or set a fixed number of retries, or put a re-connection section inside the begin/rescue scope.

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-input-wmi/issues/4. Let's continue the discussion there! :)
