### ISSUE TITLE
translate.rb: sprintf fallback value

### ISSUE THREAD

**Issue by boubou191911** [elastic/logstash-contrib#151]
In translate.rb, for the fallback value, wouldn't it be useful to perform an event.sprintf on @fallback value. Therefore the fallback value for a translate filter can contain event variable. Up to now only fixed value can be used in this field.

**Comment by wiibaa** [comment]
@boubou191911 good catch. Thanks

**Comment by jsvd** [comment]
closed by https://github.com/logstash-plugins/logstash-filter-translate/commit/271a312df32c98b35c32661690651a7e51abcc83
