### ISSUE TITLE
Nested fields and arrays for google_bigquery

### ISSUE THREAD

**Issue by thesamet** [elastic/logstash-contrib#157]
From the documentation of csv_schema it seems like only flat structures are supported. Is there any support planned for supporting nested fields and arrays?

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-output-google_bigquery/issues/8. Let's continue the discussion there! :)
