### ISSUE TITLE
puppet_facter errors on SSL

### ISSUE THREAD

**Issue by frankatwork** [elastic/logstash-contrib#158]
Getting this error ehwn loading the puppet_facter plugin.

:timestamp=>"2015-03-31T20:26:04.266000+0200", :message=>"A plugin had an unrecoverable error. Will restart this plugin.\n  Plugin: <LogStash::Inputs::PuppetFacter host=>\"x.x.x\", private_key=>\"/xpem\", public_key=>\"/x.pem\", environment=>\"production\">\n  Error: Unable to initialize, java.io.IOException: DerInputStream.getLength(): lengthTag=127, too big.", :level=>:error}

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-input-puppet_facter/issues/2. Let's continue the discussion there! :)
