### ISSUE TITLE
TLS support for riemann output

### ISSUE THREAD

**Issue by hectorj2f** [elastic/logstash-contrib#162]
We're using Logstash and Riemann, and we'd like to set a bidirectional TLS communication between the Logstash sender and the Riemann server. This configuration can be defined in Riemann however we couldn't find anyway of doing it in the logstash Riemann output.

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-output-riemann/issues/4. Let's continue the discussion there! :)
