### ISSUE TITLE
Where did the grep filter go and how can I install it in 1.5.0

### ISSUE THREAD

**Issue by brupm** [elastic/logstash-contrib#163]

**Comment by untergeek** [comment]
grep is made obsolete by the addition of conditionals in 1.4

See https://www.elastic.co/guide/en/logstash/current/configuration.html#conditionals

For example, you can do regular expressions:

if [fieldname] =~ /REGEXPATTERN/ {
  # Filter block or output block bits go here, like:
  # drop {}
  # mutate { ... }
  # etc...
}

**Comment by brupm** [comment]
Thank you @untergeek do you have an example for referencing the value of a field instead of fieldname?

**Comment by untergeek** [comment]
@brupm I will answer here, but point you to our [new discussion forums](https://discuss.elastic.co/c/logstash) as the correct place to get these questions answered.

The answer is in our documentation, specifically the [field references](https://www.elastic.co/guide/en/logstash/current/configuration.html#logstash-config-field-references) section, and the [sprintf](https://www.elastic.co/guide/en/logstash/current/configuration.html#sprintf) section below that.  In short, `[fieldref]` points to a field, and `%{[fieldref]}` is the value contained in that field.  You don't technically need the `[]` if the field is root level, but if you are using sub-fields, the syntax is `%{[primary][sub]}`.
