### ISSUE TITLE
How to pass a subprotocol for the input puglin of websocket

### ISSUE THREAD

**Issue by yoelfme** [elastic/logstash-contrib#168]
Basically in Javascript I can make this
```
var ws = new WebSocket('ws://localhost:8080', 'my-own-subprotocol');
```
But the configuration for the websocket only allows the following settings

|Setting|Input Type|
|---|---|
|add_field|hash|
|codec|codec|
|mode|string, one of ["server", "client"]|
|tags|array|
|type|string|
|url|string|

[More info](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-websocket.html#_synopsis_46)

**Comment by untergeek** [comment]
This repository is for the now-deprecated Logstash 1.4.x tree and is no longer supported or acted on. 

Please look to https://github.com/logstash-plugins/logstash-input-websocket
