### ISSUE TITLE
logstash-translate: Add wildcard for field selection/Remove field requirement and add tag lookup/Translate array values

### ISSUE THREAD

**Issue by CSUMBmWall** [elastic/logstash-contrib#169]
Sorry to cram all of these requests into one heading, but any one of them could solve my issue.  
I have a field with an array of values I need translated.  Since translate only works on the first value, I renamed all of the fields dynamically to input_["value"].  Now I can't use translate on them because it requires a specific field, and I have any number of these fields that were once in an array, and are now named according to their value.  
If I could use translate on an array, could translate according to a tag, instead of a field, or if I could use a wildcard/regex/pattern for the field value, I would be a happy camper.

**Comment by untergeek** [comment]
@CSUMBmWall logstash-contrib is deprecated, as it was tied to Logstash 1.4.x, which is no longer supported.  Any requests for individual plugins should go to the respective plugin repositories at https://github.com/logstash-plugins, or for core Logstash functionality, https://github.com/elastic/logstash
