### ISSUE TITLE
Dynamic tag keys?

### ISSUE THREAD

**Issue by reinhard-brandstaedter** [elastic/logstash-contrib#170]
Hello,

this is not really an issue but more a feature request or idea.
I'm trying to create tag keys in the influx output that are based on a dynamic value.

Let me explain. Here is my message. What I'm interested in as a tag key is the businessTransactions.dimensionNames value "(y) page controller name". This array will always have one item but the associated value of this key is stored in businessTransactions.occurrences.dimensions.
```
{
  "_index": "dtbtexport-2016.06.28",
  "_type": "logs",
  "_id": "AVWYa_fONUyQIn6JVB9R",
  "_score": null,
  "_source": {
    "businessTransactions": {
      "name": "Page Type User Experience",
      "type": 1,
      "application": "B2C",
      "measureNames": [],
      "dimensionNames": [
        "(y) page controller name"
      ],
      "occurrences": {
        "startTime": 1467141114899,
        "values": [],
        "dimensions": [
          "MiniCart"
        ],
        "actionName": "click on \"Add to cart\"",
        "visitId": 433910,
        "responseTime": 216,
        "cpuTime": 28.232065808963686,
        "execTime": 290.3504825234413,
        "duration": 216,
        "failed": false,
        "clientErrors": 0,
        "convertedBy": [],
        "clientTime": 129.18971347808838,
        "networkTime": 0,
        "serverTime": 86.81028652191162
      }
    }
}
```

What I'm now trying to do is creating tags based on the dynamic (but finite) value of one field. My intuitive approach was to provide the field in the send_as_tags array:
```
influxdb {
  host => "localhost"
  db => "dynatrace"
  allow_time_override => "true"
  measurement => "%{[businessTransactions][name]}"
  data_points => {
    "responsetime" => "%{[businessTransactions][occurrences][responseTime]}"
    "businesstransaction" => "%{[businessTransactions][name]}"
    "application" => "%{[businessTransactions][application]}"
    "%{[businessTransactions][measureNames]}" => "%{[businessTransactions][occurrences][values]}"
   "%{[businessTransactions][dimensionNames]}" => "%{[businessTransactions][occurrences][dimensions]}"

   "time" => "%{[businessTransactions][occurrences][startTime]}"
  }
  send_as_tags => ["businesstransaction","application", "%{[businessTransactions][dimensionNames]}"]
}
```

But this didn't add the tag to influxdb.
Is that because fields are not allowed here or am I'm doing something wrong? Would that be a good usecase or is there another way to achieve this?

Thanks for any feedback!

**Comment by untergeek** [comment]
I apologize, but this repository is deprecated.  It was for the 1.4 branch of Logstash, which is no longer supported.

If you're looking for help with the influxdb output, you can raise it at https://discuss.elastic.co/c/logstash

If you need to report an issue, or submit a pull request, you can do it at https://github.com/logstash-plugins/logstash-output-influxdb
