### ISSUE TITLE
improvement #918 lost

### ISSUE THREAD

**Issue by drenty** [elastic/logstash-contrib#34]
See: https://github.com/elasticsearch/logstash/commit/06bee7a25f29bb674c5ab58bf51b24c42159942d

Maybe it affects other plugins.

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-input-wmi/issues/7. Let's continue the discussion there! :)
