### ISSUE TITLE
Support for URL in JMX input

### ISSUE THREAD

**Issue by gbutt** [elastic/logstash-contrib#73]
In order to connect logstash to my JMX server I need to pass the url parameter when creating the MBean connection. For example:

jmx_connection = JMX::MBean.connection :url => thread_hash_conf['url'],
                                                 :username => thread_hash_conf['username'],
                                                 :password => thread_hash_conf['password']

This should be an easy enhancement yes? :beers:

**Comment by suyograo** [comment]
Fixed in https://github.com/logstash-plugins/logstash-input-jmx
