### ISSUE TITLE
RFC5424 output seems to format zone offset incorrectly

### ISSUE THREAD

**Issue by intjonathan** [elastic/logstash-contrib#76]
When sending syslog output in rfc5424 mode, the output looks like this:
```
<141>1 2014-06-17T17:55:25.000+0000 twitter LOGSTASH - - - I'm hiring! Vice President, Residential Practice  at PECI - Portland, Oregon Area #jobs http://t.co/mS2qJaPwPN
```
The TZ offset in the timestamp shows +0000. The RFC [specifies this](http://tools.ietf.org/html/rfc5424#section-6.2.3) should be a `Z` (or `+00:00`) instead of `+0000`. It does not permit numeric time offsets which lack a `:` separator. This leads to parse errors on downstream systems, which is no fun.

The code path starts in the [syslog output](https://github.com/elasticsearch/logstash-contrib/blob/master/lib/logstash/outputs/syslog.rb#L129), which delegates an sprintf of the time format to [event#sprintf](https://github.com/elasticsearch/logstash/blob/master/lib/logstash/event.rb#L186). I'm guessing the `.SSSZ` element in the format string could be changed to something that produces compliant output.

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-output-syslog/issues/3. Let's continue the discussion there! :)
