### ISSUE TITLE
Gem conflict with mime-types

### ISSUE THREAD

**Issue by alejo90** [elastic/logstash-contrib#84]
Hi, after installing contrib via bin/plugin install on logstash 1.4.2, when the email output is activated, I get

    Gem::LoadError: Unable to activate mail-2.5.3, because mime-types-2.3 conflicts with mime-types (~> 1.16)
      raise_if_conflicts at file:/srv/logstash-1.4.2/vendor/jar/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/specification.rb:2000
                activate at file:/srv/logstash-1.4.2/vendor/jar/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/specification.rb:1238
            try_activate at file:/srv/logstash-1.4.2/vendor/jar/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems.rb:194
                 require at file:/srv/logstash-1.4.2/vendor/jar/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:132
                 require at file:/srv/logstash-1.4.2/vendor/jar/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:124
                 require at /srv/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/polyglot-0.3.4/lib/polyglot.rb:65
                register at /srv/logstash-1.4.2/lib/logstash/outputs/email.rb:107
                    each at org/jruby/RubyArray.java:1613
            outputworker at /srv/logstash-1.4.2/lib/logstash/pipeline.rb:220
           start_outputs at /srv/logstash-1.4.2/lib/logstash/pipeline.rb:152

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-output-email/issues/25. Let's continue the discussion there! :)
