### ISSUE TITLE
spec/sqlite hardcoded path to database

### ISSUE THREAD

**Issue by wiibaa** [elastic/logstash-contrib#93]
Initially reported in https://logstash.jira.com/browse/LOGSTASH-2235

The following line hardcode the absolute path to test-database
https://github.com/elasticsearch/logstash-contrib/blob/master/spec/sqlite-test.rb#L59

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-input-sqlite/issues/1. Let's continue the discussion there! :)
