### ISSUE TITLE
Allow elasticsearch filter to specify index

### ISSUE THREAD

**Issue by kurtado** [elastic/logstash-contrib#95]
Currently, the only configuration options are fields, host, query and sort. As far as I can tell, it is not possible to specify the index in a query string.

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-filter-elasticsearch/issues/14. Let's continue the discussion there! :)
